### ISSUE TITLE
bin/test practice/two-fer fails for me locally on main

### ISSUE THREAD

**Issue by kytrinyx** [exercism/gleam#141]
I'm trying to get my setup working so that I can contribute a bit to this track, and I've followed the instructions on the gleam.run site for getting gleam and erlang installed (MacOS).

I have the latest changes on `main` locally, and am running:

```
$ bin/test practice/two-fer
```

This fails with the following output:

```
Downloading packages
 Downloaded 2 packages in 0.03s
  Compiling two_fer
error: Syntax error
  ┌─ ./src/two_fer.gleam:4:14
  │
4 │   "One for " <> option.unwrap(name, "you") <> ", one for me"
  │              ^ This operator has no value on its right side.
```

I know nothing about Gleam (yet), so my first thought is that I might have a version mismatch.

Locally I have:

```
$ gleam --version
gleam 0.23.0
```

I looked at the files in `exercises/practice/two-fer` and found a `gleam.toml`, which says:

```
gleam_stdlib = "~> 0.26"
```

Does this look right? Am I barking up the wrong tree with this?

Any pointers would be much appreciated!

**Comment by lpil** [comment]
Heya! The `<>` operator was introduced in v0.24 so you'll need to upgrade. The latest is v0.26.

Which method did you use in the documentation? I'm surprised that you've got an older version there. If you're using brew it says [here](https://formulae.brew.sh/formula/gleam) that it has the latest version, so `brew upgrade gleam` may be what you want.

**Comment by kytrinyx** [comment]
@lpil I used `brew install gleam`.

I just tried `brew upgrade gleam` and got the following:

```
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
==> Updated Homebrew from 4cf365f6c to 31ed6906f.
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
check-jsonschema

You have 13 outdated formulae and 1 outdated cask installed.
You can upgrade them with brew upgrade
or list them with brew outdated.

Warning: gleam 0.23.0 already installed
```

It's really odd that I'm not getting a newer version, as brew seems to be as up-to-date as I can get it.

> This isn't a very nice experience, I need to implement that ticket for having a friendly error message for when the Gleam version is too low.

So many tickets, so little time ❤️

**Comment by kytrinyx** [comment]
Ok, I'm really confused.

I did a `brew info gleam` and it says:

```
$ brew info gleam
==> gleam: stable 0.23.0 (bottled)
✨ A statically typed language for the Erlang VM
https://gleam.run
/usr/local/Cellar/gleam/0.23.0 (8 files, 16.0MB) *
  Poured from bottle on 2023-01-20 at 16:28:23
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/gleam.rb
License: Apache-2.0
==> Dependencies
Build: rust ✘
Required: erlang ✔, rebar3 ✔
==> Analytics
install: 236 (30 days), 957 (90 days), 2,552 (365 days)
install-on-request: 236 (30 days), 956 (90 days), 2,549 (365 days)
build-error: 1 (30 days)
```

But if I go to https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/gleam.rb it is pointing to version 0.26.0
https://github.com/Homebrew/homebrew-core/blob/14525b53ab7fa80eae8bfb33cfee07199e24170e/Formula/gleam.rb#L4

**Comment by lpil** [comment]
If you can't figure out the required incantation for brew it may be easier to download one of our precompiled binaries and put it on your path

https://github.com/gleam-lang/gleam/releases/tag/v0.26.0

**Comment by SleeplessByte** [comment]
@kytrinyx even though this already ran automatically when you were upgrading gleam, you can always try a `brew update` just because. This should update brew itself. If it doesn't work afterwards, we can bypass whatever version is on "stable" by doing:

```shell
brew unlink gleam
brew install --HEAD gleam
```

This should get it from HEAD!

**Comment by kytrinyx** [comment]
There's got to be something wrong with my brew. (I did run `brew update` yesterday... just because :))

```
$ brew install --HEAD gleam
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/core, homebrew/cask and goreleaser/tap).
==> New Formulae
copa

You have 13 outdated formulae and 1 outdated cask installed.
You can upgrade them with brew upgrade
or list them with brew outdated.

Error: No head is defined for gleam
```

I'll go ahead and get a precompiled binary!

**Comment by kytrinyx** [comment]
Precompiled binary for the win!

That's me sorted (for now). Thanks 💙
