### ISSUE TITLE
assert True vs should.be_true in tests

### ISSUE THREAD

**Issue by kytrinyx** [exercism/gleam#148]
I noticed that the style of assertions differs between tests, and I was wondering if that is done intentionally, or if it's more of a _it doesn't actually matter_ type of thing.

E.g.

```
# exercise: leap
pub fn year_divisible_by_100_not_divisible_by_400_in_common_year_test() {
  leap.is_leap_year(2100)
  |> should.be_false
}
```

```
# exercise: pangram
pub fn case_insensitive_test() {
  let sentence = "the quick brown fox jumps over with lazy FX"
  assert False = is_pangram(sentence)
}
```

If it doesn't really matter, is it okay if I just use one style when working on the exercises? I have a (very stupid) generator that I configure, because working with the `canonical-data.json` file manually is a bit of a headache. I can do different things for each exercise if necessary, but if it doesn't matter it's easier to be consistent.

**Comment by jiegillet** [comment]
I personally like the `should.be_false` style, I think I will include that in my generator too.

**Comment by kytrinyx** [comment]
Cool, I will stick with that, then!

**Comment by lpil** [comment]
should.be_true produces a worse error and will be removed in future so using the assert keyword is preferred. Later it will be possible to write "assert someexpression", at which point we will migrate to that.

**Comment by jiegillet** [comment]
Oops, sorry @kytrinyx

**Comment by lpil** [comment]
Thanks gang 💜

**Comment by kytrinyx** [comment]
What should this look like with the other style assertion?

```
pub fn another_four_tile_test() {
  {
    [#(6, 4), #(6, 2), #(2, 0), #(4, 0)]
    |> arrange
    |> list.length > 0
  }
  |> should.be_true
}
```

**Comment by jiegillet** [comment]
I see some options. In ascending order of personal preference:
```gleam
pub fn one_tile_test() {
  assert True =
    [#(2, 2)]
    |> arrange
    |> list.length > 0
}
```

```gleam
pub fn one_tile_test() {
  assert False =
    [#(2, 2)]
    |> arrange
    |> list.is_empty
}
```

```gleam
pub fn one_tile_test() {
  assert [_, ..] = arrange([#(2, 2)])
}
```
but if I was going with the last one, I would change the `should.equal(0)` tests to
```gleam
pub fn another_impossible_three_tile_test() {
  assert [] = arrange([#(5, 3), #(4, 5), #(2, 3)])
}
```

**Comment by suraj-mandal** [comment]
I have added some exercises where the tests are using should_be.true, should I switch that to Assert?

**Comment by kytrinyx** [comment]
@suraj-mandal Yes, please—anything new should be using `assert`. Thanks for asking!

**Comment by ErikSchierboom** [comment]
I just searched for `should.be_true` in the code base, and didn't find any results. I think this can be closed?

**Comment by lpil** [comment]
I guess so! Fab!
