### ISSUE TITLE
The test case will not succeed because it is not an Armstrong number

### ISSUE THREAD

**Issue by ymadd** [exercism/gleam#183]
The following test case should return False because it is not an Armstrong number, not True.

You can check on the following website.
https://www.atechdaily.com/tools/check-armstrong-number
```gleam
pub fn armstrong_number_containing_seven_zeroes_test() {
  assert True =
    armstrong_numbers.is_armstrong_number(
      186_709_961_001_538_790_100_634_132_976_990,
    )
}
pub fn the_largest_and_last_armstrong_number_test() {
  assert True =
    armstrong_numbers.is_armstrong_number(
      115_132_219_018_763_992_565_095_597_973_971_522_401,
    )
}
```

**Comment by angelikatyborska** [comment]
Both are Armstrong numbers, it's just that this checker website cannot handle such big numbers. You might notice that it tries to represent them in scientific notation (e+...), losing some accuracy.

I have added exactly those two tests to the Elixir track a few days ago: https://github.com/exercism/elixir/pull/1275/files

**Comment by ymadd** [comment]
I see, so that was it. Sorry for causing trouble. Thank you for your answer.
