### ISSUE TITLE
Mistake in exercise Freelancer Rates: test and example code don't match instructions

### ISSUE THREAD

**Issue by Sterver47** [exercism/gleam#186]
Hi!

The exercise Freelancer Rates has a mismatch in the test and the example code with the instructions. The problem is in task ["4. Calculate the number of workdays given a budget, hourly rate and discount"](https://github.com/exercism/gleam/blob/main/exercises/practice/freelancer-rates/.docs/instructions.md#4-calculate-the-number-of-workdays-given-a-budget-hourly-rate-and-discount) (function `days_in_budget`).

The instruction is:
> The returned number of days should be rounded down (take the floor) to **one decimal place**.

But the example code does floor to **zero decimal places**. 

The example in the instructions states that output from `freelancer_rates.days_in_budget(20_000, 80, 11.0)` should equal `35.0`, while the correct value is `35.1`. The same applies to the test.

For reference, the Elixir track has the same exercise with the same instructions: [exercism/elixir/blob/main/exercises/concept/freelancer-rates/.docs/instructions.md](https://github.com/exercism/elixir/blob/main/exercises/concept/freelancer-rates/.docs/instructions.md#4-calculate-the-number-of-workdays-given-a-budget-hourly-rate-and-discount)

If I'm not wrong, I think there are two potential solutions to this. Either change the instructions, which will cause inconsistency in instructions for the same exercise across tracks, or make a correction to the example and test.

My solution code for the mentioned task is:
```Gleam
import gleam/float
import gleam/int

fn discounted_daily_rate(hourly_rate: Int, discount: Float) -> Float {
  billable_hours *. apply_discount(hourly_rate, discount)
}

pub fn days_in_budget(budget: Int, hourly_rate: Int, discount: Float) -> Float {
  let round_to_one_decimal = fn(x: Float) -> Float {
    float.multiply(x, 10.0)
      |> float.floor
      |> fn(x) { x /. 10.0 }
  }

  int.to_float(budget) /. discounted_daily_rate(hourly_rate, discount)
    |> round_to_one_decimal
}
```

But as an absolute newbie in Gleam, I'm not sure if this is the correct way to do it and if we can use my code as an example code.

I'll be glad for any input.

**Comment by lpil** [comment]
Oh dear! I'm not sure what has happened here or what is best. @jiegillet do you have thoughts here?

**Comment by suraj-mandal** [comment]
Can I check this one out?

**Comment by jiegillet** [comment]
I had a look at this.

First off, rather surprisingly, that exercise is not a common practice exercise, it's used as a concept exercise on several different tracks to teach about floats. That means that there is no "official" tests, so it's up to tracks to deal with this.
This exercise is notorious for being easy to misunderstand, and I don't hold it close to my heart.

Like @Sterver47, I also think it was been ported from the Elixir track: instructions and solutions are almost identical although the tests are different... However, the Gleam example solution doesn't handle the rounding correctly, it always floors the answer to the lowest whole number, **contradicting the instructions**.

So, yes, we could either fix the instructions or the solution (the solution above seems fine to me at a glance), but there is a third option: get rid of the exercise until we have a proper, carefully built concept syllabus.

@kytrinyx I would love to get your opinion on this.

**Comment by kytrinyx** [comment]
Exercises that make good concept exercises typically make terrible practice exercises. I am not sure how we ended up with this exercise in problem specs as that repo is only for practice exercises.

My vote would be to delete the exercise.

I will also think about what to do about the entry in the problem specs repo.

**Comment by kytrinyx** [comment]
Oh! I see what you mean by "ported from Elixir". There's no entry in problem specs. That's easier then.

Yeah, so I definitely recommend dropping this exercise out of the practice exercises.

**Comment by lpil** [comment]
Fab, that's an easy solution. Let's drop it.

**Comment by Sterver47** [comment]
Well, this escalated quickly. But I see why dropping it is the best option.

**Comment by kytrinyx** [comment]
Here are the docs for how to drop it: https://exercism.org/docs/building/tracks/deprecated-exercises

**Comment by lpil** [comment]
Thanks everyone!
