### ISSUE TITLE
Configure online editor

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/gleam#23]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

In Exercism v3, students can now choose to work on exercises directly from their browser, instead of having to download exercises to their local machine. The track-specific settings for the in-browser editor are defined in the top-level `"online_editor"` field in the track's `config.json` file. This field is defined as an object with two fields:

- `"indent_style"`: the indent style, either "space" or "tab".
- `"indent_size"`: the indent size, which is an integer (e.g. 4).

You can find a full description of these fields in [the spec](https://github.com/exercism/v3-docs/blob/main/anatomy/tracks/config-json.md#metadata).

## Goal

The `"online_editor"` field should be updated to correspond to the track's best practices regarding indentation.

## Example

```json
"online_editor": {
  "indent_style": "space",
  "indent_size": 4
}
```

## Tracking

https://github.com/exercism/v3-launch/issues/2

**Comment by hsadia538** [comment]
@lpil  I have started working on it. Should the highlightJS language for this remain as Rust?

**Comment by lpil** [comment]
If we can add our own config there is one for Gleam here https://github.com/gleam-lang/gleam/blob/88015db9562dc5218c5e389574ae8672b0d937b1/compiler-core/templates/highlightjs-gleam.js

**Comment by hsadia538** [comment]
@lpil  its not mentioned in the list of identifiers as per [this](https://github.com/exercism/docs/blob/main/building/tracks/config-json.md)

How should I refer it

**Comment by lpil** [comment]
I don't know, I only know about Gleam I'm afraid. You'll need to look into the Exercism documentation or keep it as the the Rust syntax.

**Comment by ErikSchierboom** [comment]
@lpil Is there an NPM package for the gleam highlightjs functionality?

**Comment by lpil** [comment]
No but I can make one if that's useful

**Comment by hsadia538** [comment]
@ErikSchierboom please close the issue if no changes are required and is already up to date

**Comment by ErikSchierboom** [comment]
@lpil An NPM package would be perfect!
