### ISSUE TITLE
Syntax highlighting in web editor

### ISSUE THREAD

**Issue by lpil** [exercism/gleam#231]
It would be fab to have syntax highlighting in the web editor! How do we do this?

**Comment by jiegillet** [comment]
I believe the syntax highlighting is powered by codemirror plugins.
https://codemirror.net/examples/lang-package/
I don't know much more about it

**Comment by ErikSchierboom** [comment]
That is correct. We are using codemirror so you'll need to build a codemirror plugin. It might be worth posting on our forums to see if there are people that know about this/can help with this.

**Comment by rokf** [comment]
This issue can probably be closed since https://github.com/exercism/codemirror-lang-gleam exists and highlighting is working.

Am I missing something?

**Comment by lpil** [comment]
Thank you
