### ISSUE TITLE
Concepts exercises

### ISSUE THREAD

**Issue by lpil** [exercism/gleam#276]
Time to make a syllabus!

F# and Elm have been excellent references for concepts and exercises as they have similar features to Gleam.

[This page](https://exercism.org/docs/building/tracks/stories) is useful for finding exercises used by other tracks for concepts.

Here's a list of all the concepts that I have identified, using the Elixir track as a base.

- [x] anonymous-functions
- [x] basics
- [x] bitstrings
- [x] bools
- [x] case-expressions
- [x] constants
- [x] custom-types
- [x] external-functions
- [x] external-types
- [x] floats
- [x] generics
- [x] guards
- [x] ints
- [x] io
- [x] iterators
- [x] labelled-arguments
- [x] labelled-fields
- [x] let-assertions
- [x] lists
- [x] maps
- [x] modules
- [x] nil
- [x] opaque-types
- [x] options
- [x] orders
- [x] pipe-operators
- [x] phantom-types
- [x] queues
- [x] recursion
- [x] regular-expressions
- [x] results
- [x] sets
- [x] strings
- [x] tail-call-recursion
- [x] tuples
- [x] type-aliases
- [x] use-expressions

**Comment by bcpeinhardt** [comment]
Looks awesome :) The Elixir track seems to have a concept on processes, pid, tasks, and genserver. If the Gleam track had something similar (I guess pid, processes, tasks, actor, and maybe even supervisor), it would be immensely helpful to beam newbies like me. There's not really an existing resource that teaches BEAM with Gleam, and I think Gleam is gonna be picking up a lot of developers who've never done BEAM before (like me). Would any of that be in scope for the track?

**Comment by lpil** [comment]
I think that'd be great too! I omitted them as I wanted to get the basics of the language down first, but would be good to have for sure.
