### ISSUE TITLE
Labels in Darts exercise

### ISSUE THREAD

**Issue by giacomocavalieri** [exercism/gleam#310]
The Dart's exercise defines its function stub as:

```gleam
pub fn score(x x: Float, y y: Float) -> Int {
  todo
}
```

which is perfectly fine; however, it's one of the first suggested exercises in the syllabus for the `case` lesson.
Since case is one of the first lessons the student is never introduced to labelled arguments before and seeing a function with `x x: Float` as an argument may be confusing

I propose we change the exercise to remove the labels to make it less surprising for someone whose learning gleam through the syllabus

**Comment by lpil** [comment]
Good idea. Let's remove them.

**Comment by giacomocavalieri** [comment]
Great! As soon as I have a couple spare minutes I'll get to it 👍
