### ISSUE TITLE
The Go exercise doesn't say anything about implementing a `change_player` function

### ISSUE THREAD

**Issue by michallepicki** [exercism/gleam#317]
When solving the Go exercise, I was instructed to implement the `apply_rules` function, so I did:
```gleam
pub fn apply_rules(
  game: Game,
  rule1: fn(Game) -> Result(Game, String),
  rule2: fn(Game) -> Game,
  rule3: fn(Game) -> Result(Game, String),
  rule4: fn(Game) -> Result(Game, String),
) -> Game {
  {
    use game <- result.try(rule1(game))
    let game = rule2(game)
    use game <- result.try(rule3(game))
    use game <- result.try(rule4(game))
  } |> unwrap_map_error(fn(e){ Game(..game, error: e) })
}

fn unwrap_map_error(result: Result(a, b), fun: fn(b) -> a) -> a {
  case result {
    Ok(val) -> val
    Error(e) -> fun(e)
  }
}
```

but the tests fail with:
<img src="https://github.com/exercism/gleam/assets/4972756/5a4dd60d-2126-4204-880d-36eaf3e20aed" width="400px">

even though there was no mention of having to implement a `change_player` function

**Comment by lpil** [comment]
Oh no! Sorry this was my mistake

**Comment by lpil** [comment]
Hey! That function is defined in the test module. There's a little bug in your code, but unfortunately because of how Exercism works you can't see the warning that the compiler is emitting as compilation was successful.

```gleam
    use game <- result.try(rule4(game))
  } |> unwrap_map_error(fn(e){ Game(..game, error: e) })
```
Here there's no expression after the `use`, so the compiler inserts a `todo` as the empty function body.

Perhaps there's a better behaviour for the compiler?

**Comment by michallepicki** [comment]
Oooh, I see the bug. Thank you! I was confused because I glanced at the [example solution](https://github.com/exercism/gleam/blob/main/exercises/concept/go/.meta/example.gleam) which also has a similarly named function, but now I see it's private.

**Comment by lpil** [comment]
Hayleigh has pointed out that this wouldn't be so confusing if the test runner stated where the todo was in the code, I shall add that!
