### ISSUE TITLE
wine-cellar question

### ISSUE THREAD

**Issue by eppolito** [exercism/gleam#330]
## Issue
When solving the exercise in exercises/concept/wine-cellar/, I keep getting a rather cryptic error.
```
error: Unexpected labelled argument
   ┌─ /path/to/exercism/gleam/wine-cellar/test/wine_cellar_test.gleam:75:25
   │
76 │   |> wine_cellar.filter(color: White, country: "Germany")
   │                         ^^^^^^^^^^^^

This argument has been given a label but the constructor does
not expect any. Please remove the label `color`.
```

## Steps to Reproduce
1. Make a fresh clone of the exercise using the `exercism` CLI.
2. Run `gleam test` in the root of the clone.

## Further Information
1. No error when running tests from https://github.com/gleam-lang/gleam/issues/1097.
2. As the compiler suggests, the error goes away when the labels are removed (though this defeats the purpose of the exercise).
3. I think the error may originate in https://github.com/exercism/gleam-test-runner.  A recent commit has the message "Include positional information", but I'm new to gleam and can't make sense of that file.

## Versions
Gleam: `gleam 0.30.5`
Exercism CLI: `exercism version 3.1.0`
OS: `Pop_OS! 22.04 LTS`

**Comment by eppolito** [comment]
On further reflection, the error isn't cryptic.  The cause of the error is the bit that doesn't make sense.

**Comment by lpil** [comment]
Hi @eppolito ! This exercises is teaching labelled arguments, so the student is expected to define them I'll add a comment to make this clearer.

**Comment by eppolito** [comment]
Sorry, should have mentioned that the error persists when I add them to the signature of the function `filter`.  This is what I have:
```
pub fn filter(wines: List(Wine), color: Color, country: String) -> List(Wine) {
  todo
}
```
Maybe I'm just not doing that correctly?

PS. Thanks @lpil for designing Gleam.  This is probably the most pleasant language I've ever used: batteries included like rust, with immutability and types reminiscent to that of Haskell.  Absolutely beautiful!

**Comment by lpil** [comment]
Thank you for the support, it means a lot 💜 

You've nearly got the right answer- you just need to add labels to those arguments. I won't type the answer here, as to not ruin the challenge :)

**Comment by eppolito** [comment]
Aha!  I failed to realize that argument names and argument labels are not the same thing \*facepalm\*.  Thanks so much again @lpil.  Closing this (non-)issue.
