### ISSUE TITLE
Old methods used in the Set introduction

### ISSUE THREAD

**Issue by fmesteban** [exercism/gleam#343]
The Introduction to Sets has the wrong name for some methods `set.remove` instead of `set.delete` and `set.intersect` instead of `set.intersection`

To not open another issue, there's a minor issue with one of the exercises for the Set concept,  "Gotta Snatch 'Em All":

Theres a remove_duplicates fn to complete with no input from the exercise (although it's obvious what it should do)

**Comment by lpil** [comment]
Thank you
