### ISSUE TITLE
Secure Treasure Chest - Error Instructions

### ISSUE THREAD

**Issue by rokf** [exercism/gleam#363]
The instructions on the `Secure Treasure Chest` exercise don't say what `Error` message (`String`) is expected to be set to.

I see two options:

1. The messages are added into the descriptions.
2. The tests are updated in such a way that the error message doesn't matter.

I'd personally prefer the second option since the error message doesn't really add anything to the exercise in my opinion 🙂

**Comment by lpil** [comment]
The former please. Thank you.
