### ISSUE TITLE
Erlang Extraction Exercise - Deletion Hint Mistake

### ISSUE THREAD

**Issue by rokf** [exercism/gleam#370]
Hi 😄 The deletion hint (task 4) in the Erlang Extraction exercise has a mistake.

![CleanShot 2023-10-15 at 20 53 14](https://github.com/exercism/gleam/assets/2836852/15623c50-5430-4e97-bc02-215df40da3e0)

![CleanShot 2023-10-15 at 20 56 03](https://github.com/exercism/gleam/assets/2836852/0d45ee24-72f0-4c85-bfdf-b83f34782a71)

The functions have two arguments, not three.

https://www.erlang.org/doc/man/gb_trees#delete_any-2

**Comment by rokf** [comment]
The hints could mention the order of the arguments as well, just as the hint for the previous task (insert / task 3). In case that this would give away too much information it could remain as it is 😄 I'm personally fine with both options.

**Comment by lpil** [comment]
Thank you
