### ISSUE TITLE
High school sweetheart test case is annoying

### ISSUE THREAD

**Issue by mcastorina** [exercism/gleam#394]
This exercise asks you to create and return ASCII art such as:

```
  //      ******       ******
  //    **      **   **      **
  //  **         ** **         **
  // **            *            **
  // **                         **
  // **     X. X.  +  X. X.     **
  //  **                       **
  //    **                   **
  //      **               **
  //        **           **
  //          **       **
  //            **   **
  //              ***
  //               *
```

But the test looks for exact matching characters (including whitespace!). As a student this is super annoying because my solution *works* it just doesn't have the exact same whitespace as the test. I ended up copying the test error message output so I could tick of the exercise and move on.

Suggestions for improvement:
* Remove task / test for creating ASCII art
* Make the test more lenient
  * Check that the string contains the two initials, for example

I'd be happy to contribute the changes if others agree.

**Comment by lpil** [comment]
If we did that how would we verify that the heart is in the correct format?

I'm sorry, I don't understand how the programmer could construct the heart correctly and the current test incorrectly think it is not right. Could you give some example code that triggers this? Thank you

**Comment by mcastorina** [comment]
Here's an example solution to `pair` using the commented out ASCII art which fails the test.

```gleam
pub fn pair(full_name1: String, full_name2: String) {
  let i1 = initials(full_name1)
  let i2 = initials(full_name2)
"
        ******       ******
      **      **   **      **
    **         ** **         **
   **            *            **
   **                         **
   **     "<>i1<>"  +  "<>i2<>"     **
    **                       **
      **                   **
        **               **
          **           **
            **       **
              **   **
                ***
                 *
"
}
```

**Comment by lpil** [comment]
It's testing the ability of the programmer to build a string exactly as directed. It is normal for string formatting to need to be exact.

**Comment by mcastorina** [comment]
[Learning Objectives](https://github.com/exercism/gleam/blob/main/exercises/concept/high-school-sweetheart/.meta/design.md#learning-objectives)

> Learn about the pipe operator by helping high school sweethearts profess their love on social media via ASCII art.

If the goal is to teach the pipe operator, I don't think fiddling with ASCII art whitespace is a good exercise. If the goal of the exercise is to teach string formatting, I would understand your argument. But I guess we're in disagreement.

Feel free to close this issue; it'll at least be a log of my poor experience on this exercise in case other students experience the same.
