### ISSUE TITLE
Case Expressions

### ISSUE THREAD

**Issue by europe1** [exercism/gleam#399]
Hey,

[Here](https://github.com/exercism/gleam/blob/main/concepts/case-expressions/about.md) it says
> For performance reasons only basic mathematical and boolean operators are allowed in guards, other functions cannot be used in guards.

I don't see a way to use any mathematical operator in a case guard, it always throws an exception. Also did not find any mention of this in the [Gleam Tour](https://gleam.run/book/tour/case-expressions.html).

**Comment by michallepicki** [comment]
AFAIK there is a plan to support arithmetic expressions in guards, but it's not implemented yet: https://github.com/gleam-lang/gleam/issues/1756

**Comment by lpil** [comment]
Yup, that's right!
