### ISSUE TITLE
Replace/Refactor High-School sweetheart exercise

### ISSUE THREAD

**Issue by Gitznik** [exercism/gleam#439]
Hi there, thanks for putting all the effort into the exercism stuff. It's really nice getting into gleam with them :)

I just did the High-School Sweetheart exercise, and IMO it is not a great exercise. I had the pipe related stuff done in a minute, and then struggled for a couple to get the heart formatting to match the exact expected output (which according to the exercise description expected `//  ` before every line, which was not what the test expected).

IMO putting the names into the heart is an annoying task that does not help conveying how to use the pipe operator, and should be removed/reworked.

**Comment by lpil** [comment]
Hello! I don't have funding to make Exercism content currently, but you are welcome to have a go. Thanks!
