### ISSUE TITLE
reference to fsharp in instructions markdown

### ISSUE THREAD

**Issue by daneroe** [exercism/gleam#492]
Very minor, but noticed while doing the exercise locally

https://github.com/exercism/gleam/blob/b321e3afc51c3bb41ca6a469ffeae72e5c618c5d/exercises/concept/bandwagoner/.docs/instructions.md?plain=1#L82C1-L84C1

by extension, colours for that code block are rendering a bit off on the website

https://exercism.org/tracks/gleam/exercises/bandwagoner

Great site and track (and language) BTW!

**Comment by Varpie** [comment]
Corrected in #500, which has been merged. I don't think that I can close this issue, but you can verify it and close it yourself.

**Comment by daneroe** [comment]
Awesome, thanks :)
