### ISSUE TITLE
Change Bowling exercise, or remove.

### ISSUE THREAD

**Issue by hagenek** [exercism/gleam#502]
I spent over 10 hours on this exercise, and I see I am not alone in finding it a bit hard // Much work. It only has 36% completion rate.

Maybe setting it up with a different data structure, or giving all the rolls at once would be better.

**Comment by lpil** [comment]
Hello! Yes, the bowling exercise is quite challenging. It's not defined here, but instead is one of the standard exercism exercises, so if you wish to discuss changes to it then the forum would be the place to go.
