### ISSUE TITLE
Extract track-specific help instructions from `config/exercise_readme.go.tmpl`

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/gleam#58]
Each track needs a file that contains track-specific instructions on how to get help. The contents of this document are only presented to the student when using the CLI. This file lives at `exercises/shared/.docs/help.md`. **You almost certainly already have this information, but need to move it to the correct place.**

For v2 tracks, this information was (usually) included in the readme template found at `config/exercise_readme.go.tmpl`. As such, tracks can extract the help instructions from the `config/exercise_readme.go.tmpl` file to the `exercises/shared/.docs/help.md` file.

See https://github.com/exercism/csharp/pull/1557/files for an example PR.

# Tracking

https://github.com/exercism/v3-launch/issues/50

**Comment by hsadia538** [comment]
Can I get assigned here @ErikSchierboom

**Comment by ErikSchierboom** [comment]
Sure!

**Comment by hsadia538** [comment]
@ErikSchierboom  the current 
`config/exercise_readme.go.tmpl` does not seem to have help instructions.
Also, Should I create the directory `excercises/shared/.docs` as no such exists as of now?

**Comment by ErikSchierboom** [comment]
@hsadia538 Yes, and it should have two files: `help.md` and `tests.md`. See [the documentation](https://exercism.org/docs/building/tracks/shared-files) for guidance on what the contents of those files should be.

**Comment by lpil** [comment]
Thank you @hsadia538 !

**Comment by hsadia538** [comment]
@ErikSchierboom 
do we have a gitter channel or forum for gleam?
also I was unable to find the exercise track for gleam, why is that so?

**Comment by ErikSchierboom** [comment]
@hsadia538 I don't know of a specific gitter channel. If you email me at erik @ exercism.org, I can give you access to the Exercism slack.

As for which the Gleam track is not on Exercism yet, that is because it is not done. https://github.com/exercism/gleam/issues/32 contains a list of the things that need to happen for it to become active. Are you interested in getting the Gleam track launched?

**Comment by hsadia538** [comment]
Yes, I am interested in doing so.
I have dropped you an email as well.

I was asking about the hitter channel as I was unsure as to what should I add in help.md and tests.md
@ErikSchierboom

**Comment by ErikSchierboom** [comment]
> I was asking about the gitter channel as I was unsure as to what should I add in help.md and tests.md

- The `tests.md` file should contain a concise description on how to run the tests
- The `help.md` file should link to any track-specific resources that could be useful to the student when trying to fix errors

See https://github.com/exercism/csharp/blob/main/exercises/shared/.docs/tests.md and https://github.com/exercism/csharp/blob/main/exercises/shared/.docs/help.md for examples.

**Comment by lpil** [comment]
Hey @hsadia538 ! I can help with any specific questions around Gleam.

For that one I think we could have something like this:

> You can run the tests by opening the terminal in the exercise's directory, and then running `gleam test`.

**Comment by hsadia538** [comment]
Alright, thanks a lot I will create a PR shortly on this.

**Comment by giacomocavalieri** [comment]
@lpil this seem to have been fixed by #83, so maybe we could close it? Or is there anything missing?

**Comment by lpil** [comment]
I think so! Thank you
