### ISSUE TITLE
Update exercise example solutions to be in a single file rather than a directory

### ISSUE THREAD

**Issue by lpil** [exercism/gleam#67]
Currently there is a directory per example for the example solutions. https://github.com/exercism/gleam/tree/4785ad22aec65c3fa89ebc4495775ceac5946559/exercises/practice/hello-world/example

Remove this directory in favour of a single module file. `$EXERCISE/example/thing.gleam` -> `$EXERCISE/example.gleam`.

**Comment by Callum-Irving** [comment]
Can I help with this?

**Comment by angelikatyborska** [comment]
@lpil The current convention is that the example should be in a `.meta` directory, see: https://github.com/exercism/docs/blob/main/building/tracks/practice-exercises.md#example-1

@ErikSchierboom recently did mass PRs to all the active tracks to make this change.

**Comment by lpil** [comment]
AH, good to know, thank you. I'll reopen this so that we can move it to this new location.

**Comment by hsadia538** [comment]
Can I work on this?

**Comment by ErikSchierboom** [comment]
@hsadia538 Yes, sure! What needs to happen is:

- The `example.gleam` files in each exercise's directory should be moved to `.meta/example.gleam`
- The exercise's `.meta/config.json` file's `example` key should be updated to use the new `.meta/example.gleam` file location
- The root `config.json`'s `files.example` key should change to `.meta/example.gleam`

Let me know if you need any help.

**Comment by lpil** [comment]
Thank you @hsadia538 !

**Comment by hsadia538** [comment]
@ErikSchierboom @lpil I have created a pull request, can you please take a look? Thanks
