### ISSUE TITLE
Gleam is not found

### ISSUE THREAD

**Issue by var-che** [exercism/gleam#85]
Hello
I have searched exercism website for the Gleam section and it is not found. Did you remove it or there is a bug with it?

Thanks

**Comment by angelikatyborska** [comment]
Hi! There's no bugs and nothing has been removed - the Gleam track simply doesn't have enough exercises yet to be published.

**Comment by ErikSchierboom** [comment]
If you're interested in helping us build the Gleam track, send me email to erik @ exercism.org, and I'll explain how to help get the Gleam track launched,
