### ISSUE TITLE
Track not available on Exercism

### ISSUE THREAD

**Issue by wutania** [exercism/gleam#86]
Hello! It seems like the link to this track is no longer available. I tried searching through the Exercism website as well.

I was wondering if this may be re-opened on Exercism?

Thanks!

**Comment by ErikSchierboom** [comment]
I don't think this track has ever been on the website AFAICT. If you'd like to help get the Gleam track on Exercism, could you send an email to erik @ exercism.org?

**Comment by lpil** [comment]
Yup it has never been on the website. We don't have enough exercises yet!
