### ISSUE TITLE
Run example solutions on CI

### ISSUE THREAD

**Issue by lpil** [exercism/gleam#96]
For each exercise
1. Get the solution path from the config.json file
2. Copy the example.gleam file to the solution location
3. Run `gleam test` in that project

It would be good if this script can be run locally.

The script should reset the solution file back to the original contents after the test.

**Comment by ErikSchierboom** [comment]
For inspiration, you could look at https://github.com/exercism/cobol/blob/main/bin/test or https://github.com/exercism/unison/blob/main/bin/test

**Comment by lpil** [comment]
Cool! Thank you
